import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import TopNavBar from "@/components/TopNavBar";
import {Box} from "@mui/material";

import ThemeRegistry from "@/app/theme-registry";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Object Library",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <ThemeRegistry>
            <section id={"main-section"}>

                <TopNavBar/>
                <Box id={"content"}>
                    <Box id={"inner-content"}>
                        {children}
                    </Box>
                </Box>
            </section>
        </ThemeRegistry>

        </body>
        </html>
    );
}
